### ISSUE TITLE
Breaking python binding changes with 14.0.0 release

### ISSUE THREAD

**Issue by mrj0n3s** [lief-project/LIEF#1018]
**Describe the bug**
In versions prior to the 14.0.0 release the python bindings would accept bytes and strings. Now they strictly enforce string types. One example where this can cause issues is section.search_all, I haven't managed to use the API as intended as I have to convert the data to a string. This doesn't make sense as the underlying section.search (which is used by search_all) supports bytes. This also affects calls like add_library and add_entry used for rebuilding PEs.

To fix this most binding should allow str and byte arguments using Union[str,bytes]

**Comment by romainthomas** [comment]
Could you be more precise about what are the breaking changes between `0.13.2` and `0.14.0` because from the typing definition, those `search` functions did not change:

**0.13.2**

https://github.com/lief-project/LIEF/blob/2d9855fc7f9d4ce6325245f8b75c98eb7663db60/api/python/lief/__init__.pyi#L242-L251

**0.14.0**

https://github.com/lief-project/LIEF/blob/16962f2f36a51b2acefad9cec3622f6de5730aa3/api/python/lief/__init__.pyi#L223-L232

**Comment by mrj0n3s** [comment]
the typing definition did not change but it seems like it wasn't strictly enforced before and this likely affects all bindings with str: str types.

If you try **search_all** (not search), with 13.2 you can pass bytes as an argument.
In my case **b'\xecpqmhEq\xde\x03\xb4'** if you do that with 14.0 you will get an error as it will only accept strings, and I haven't found a way to successfully search for that sequence with **search_all** in 14.0

**Comment by romainthomas** [comment]
Indeed
