### ISSUE TITLE
lief.ELF.Section and raw bytes

### ISSUE THREAD

**Issue by JonathanSalwan** [lief-project/LIEF#12]
Hey,

`lief::ELF::Section::content` and `lief::ELF::Section::data` are cool but return a list. Is it possible to get something like `lief::ELF::Section::raw` which returns raw bytes? Same with segments.

**Comment by romainthomas** [comment]
Are you talking about the Python API and the Python ``bytes`` type ?

**Comment by JonathanSalwan** [comment]
yep

**Comment by romainthomas** [comment]
TL;DR: Due to a compatibility problem between Python 3 and Python 2, I will keep the ``list`` type

Actually, the C++ underlying type of a Python ``list`` is a ``std::vector<uint8_t>``. With Python 3 and by using pybind11, we can return ``bytes`` type as follow:

```cpp
std:vector<uint8_t> foo(10);
return py::bytes(foo)
```
But I get an issue with Python 2.7. No ``bytes`` and pybind11 seems not able to cast to ``bytearray``

Moreover ``bytes`` and ``bytearray`` support ``list`` constructor: 

```python
my_bytes = bytes([1, 2, 3, 4])
my_bytearray = bytearray([1, 2, 3, 4])
```
