### ISSUE TITLE
ELF: FINI_ARRAY not updated in ELF header when array moved to another location

### ISSUE THREAD

**Issue by lousticator** [lief-project/LIEF#180]
hello Romain (and thanks for this cool utility)

i'm getting the following behavior with my big shared lib on linux, containing constructors and destructors:
 - due to transformations, the INIT_ARRAY is moved to another new address, and the FINI_ARRAY is also moved just after this new INIT_ARRAY
 - all values at these new addresses look OK in both INIT and FINI parts, and the reloc table is OK too
 - after the new lib has been saved, in the ELF private header the INIT_ARRAY address is OK, but the FINI_ARRAY still points to the old address  (ie: using 'objdump -p')
 --> everything works fine when the lib is loaded
 --> on unload, it's a segfault because the old FINI_ARRAY contains addresses which have not been relocated at dlopen()

i can try to fix it, ... but it will be easier if you give me a hint about where i should start ;-) (i've taken a look at the ELF Builder and it seems that both INIT and FINI are taken into account)

thx in advance,
eric

**Comment by lousticator** [comment]
hello @romainthomas 

at this time, unfortunately not, because the use-case only happens with this big lib...  and moreover i can't share the lib

maybe i can try to make a small sample, but up to now i have no idea on why there's a condition which makes that the INIT_ARRAY is moved to a different place

on the other side, ... i'm doing dirty traces to try to understand where the glitch happens ;-)

**Comment by apphackuno** [comment]
I am having almost the same issue here. I am trying to inject hello world into /bin/date and then hijack one of the .init_array pointers.

This is the code for my hello-world -

#include "arch/x86_64/syscall.c"
#define stdout 1

int myHello(int argc, char *argv[]) {
  asm("push %rax");
  asm("push %rcx");
  asm("push %rdx");
  asm("push %rsi");
  asm("push %rdi");
  const char msg[] = "Hello World!\n";
  _write(stdout, msg, sizeof(msg));
  asm("pop %rax");
  asm("pop %rcx");
  asm("pop %rdx");
  asm("pop %rsi");
  asm("pop %rdi");
  asm("push $0x4023b0");
  return 0;
}

The last statement pushed the address of one of the .init_array pointer.

Below is the code for my code injection:
import lief

myDate = lief.parse("/bin/date")
hello = lief.parse("hello_date")

hello_symbol = hello.get_symbol("myHello")
new_segment = myDate.add(hello.segment_from_virtual_address(hello_symbol.value))
new_entry = new_segment.virtual_address + hello_symbol.value
print new_entry
import struct
arr = struct.pack('<L', new_entry)
arr = struct.unpack('<BBH', arr)
arr = list(arr)
while len(arr) < 8:
    arr.append(0)

const_section = myDate.get_section(".init_array")
print const_section.virtual_address, const_section.content
myDate.patch_address(const_section.virtual_address, [i for i in arr])
print const_section.virtual_address, const_section.content
myDate.write("myDate")

myDate2 = lief.parse("myDate")
const_section2 = myDate2.get_section(".init_array")
print const_section2.content

Output:

======== RESTART: /home/binary/Desktop/ABA/Lec7/SBI/Lab/hookConst.py ========
8458969
6356496 [176L, 35L, 64L, 0L, 0L, 0L, 0L, 0L]
6356496 [217L, 18L, 129L, 0L, 0L, 0L, 0L, 0L]
[176L, 35L, 64L, 0L, 0L, 0L, 0L, 0L]
>>> 

Content is added to replace the original pointer with the address of the entry point. But after writing the binary, this change did not persist.

The problem seems to be from the patch_address function.

**Comment by romainthomas** [comment]
Should be fixed in LIEF v0.12.0. Feel free to re-open the issue if it is not the case
