### ISSUE TITLE
Could not install package on macOS with Python 2.7

### ISSUE THREAD

**Issue by nabla-c0d3** [lief-project/LIEF#38]
Hello,
I tried installing the Python package on macOS 10.12.5, but got an error:

```
$ pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)

$ pip install osx_lief-0.6.1_py2.7.tar.gz
Processing ./osx_lief-0.6.1_py2.7.tar.gz
Building wheels for collected packages: lief
  Running setup.py bdist_wheel for lief ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5z/wl83cz4x2blcfrfcw9s82cfr0000gn/T/pip-cKrzdw-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/5z/wl83cz4x2blcfrfcw9s82cfr0000gn/T/tmpqQbF4jpip-wheel- --python-tag cp27:
  WARNING: '' not a valid package name; please use only.-separated package names in setup.py
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying __init__.py -> build/lib
  copying setup.py -> build/lib
  error: can't copy 'ief.so': doesn't exist or not a regular file

  ----------------------------------------
  Failed building wheel for lief
```

Am I doing something wrong? The `lief.so` file in the package does work fine when imported in Python.
Thanks!

**Comment by romainthomas** [comment]
Hi @nabla-c0d3, 
Try to update your ``setuptools``:

```bash
$ pip install setuptools --upgrade
```

**Comment by nabla-c0d3** [comment]
It worked - thanks!

**Comment by diashimself** [comment]
I got this error

Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/private/var/folders/41/39h1bf895ssgkt134m67b9fr0000gn/T/pip-uninstall-guqfbN/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
