### ISSUE TITLE
Allow binary objects to calculate updated addresses after parsing

### ISSUE THREAD

**Issue by pdreiter** [lief-project/LIEF#381]
**Is your feature request related to a problem? Please describe.**
When parsing an ELF file, the original relative offsets for the file are correct for the input ELF. But when writing the ELF to an output, address and relative offsets get updated. Any new addressing gets broken.

**Describe the solution you'd like**
It would be nice to have the write/build process create a binary object.
-OR-
Some mechanism to predict sections' new offsets.

**Describe alternatives you've considered**
I'm going to write out the file, parse it again, find the relocation information in the new segment I added, then update it with the original binary's relocation.
-OR-
I immediately write the parsed binary, then read the parsed output binary and then manipulate it as I'm only manipulating the content within an added segment.

**Additional context**
A quick example of what I'm trying to do: I'm taking the lief example 05 - add a new segment, update the new segment's relocation addresses to reuse the original binary's relocation addresses for global symbols, like printf/puts.

**Comment by romainthomas** [comment]
Hello @pdreiter 

I know this issue is inconvenient while modifying a ELF/PE/Mach-O. Unfortunately, I did not find a reliable way to *precompute* section's offset as this offset will depend on the modifications that are applied on the ELF. 

For instance, the offset could be *precomputed* if you **only** add **one** section. On the other hand,
if you add a section **and** change symbol names, this offset is more complication to compute. 

> I'm going to write out the file, parse it again

I think this is the only way to do what you are looking for. Instead of having this mechanism in LIEF I would let the user to do it to avoid an implicit build that would change the internal state of the ELF binary object.

I close this issue as it is not but feel free to re-open it if find a way to handle it.
