### ISSUE TITLE
Can not find remove_dynamic_symbol in python api

### ISSUE THREAD

**Issue by zh-explorer** [lief-project/LIEF#446]
I can find `remove_dynamic_symbol ` in [C++ API document](https://lief.quarkslab.com/doc/latest/api/cpp/elf.html?highlight=remove_dynamic_symbol#_CPPv4N4LIEF3ELF6Binary21remove_dynamic_symbolEP6Symbol) but when I use python API. I find that there is not a method called  `remove_dynamic_symbol ` in [`class lief.ELF.Binary`](https://lief.quarkslab.com/doc/latest/api/python/elf.html#lief.ELF.Binary)

**Environment**
 - System: Ubuntu 18.04.4 LTS
 - Python version: Python 3.6.9
 - LIEF commit version: 0.10.1-bfe5414

**Comment by marin-m** [comment]
Hello,

Correct, also related functions such as [`remove_symbol`](https://github.com/lief-project/LIEF/blob/533b74d/src/ELF/Binary.cpp#L692) are missing in [`pyBinary.cpp`](https://github.com/lief-project/LIEF/blob/b49786f/api/python/ELF/objects/pyBinary.cpp#L463), as well as string-consuming variants. (I don't quite understand how the `remove_symbol` C++ function is meant to work however, its first call to `remove_static_symbol` seems to mean to throw an exception in case of non-success, rather than falling through to `remove_dynamic_symbol`.)

Is there a known way of how to remove a symbol in the Python binding?

Regards,
