### ISSUE TITLE
[parser] Add support for BytesIO in the python API

### ISSUE THREAD

**Issue by Rafiot** [lief-project/LIEF#49]
It would be very useful to be able to pass a bytestream (BytesIO) instead of a path to the `lief.parse` function.

**Comment by romainthomas** [comment]
I have to check how we can handle BytesIO from Python to C++. 
For PE and ELF you can use a sequence of bytes:

```python
import lief

raw = None
with open("/bin/ls", 'rb') as f:
    raw = f.read()
binary = lief.ELF.parse(raw)
print(binary)
```

**Comment by Rafiot** [comment]
Thanks!

**Comment by jhhcs** [comment]
As mentioned in #832, BytesIO is currently not working for `lief.PE.parse` because `BytesIO` objects do not have an attribute called `raw` (i.e. they do not provide an underlying `RawIOBase` object) and apparently, they do not implement the `RawIOBase` interface themselves either, because they do not have a `readall` method.
