### ISSUE TITLE
PE.Builder did not always work fine

### ISSUE THREAD

**Issue by invokerrrr** [lief-project/LIEF#529]
**Describe the bug**

The `PE.Builder` did not always work fine.

**To Reproduce**

(1) Build the following code to `win32_x86_debug.exe` (MSVC 2019 16.8.4).

```cpp
#include <cstdio>
int main() {
	std::printf("hello world!\n");
	return 0;
}
```

(2) Rebuild the PE file to `win32_x86_test.exe`.
The python code is:

```python
from lief import *
binary=PE.parse("win32_x86_debug.exe")
builder=PE.Builder(binary)
builder.build_imports(True).patch_imports(True)
builder.build()
builder.write("win32_x86_test.exe")
```

(3) Run `win32_x86_test.exe`.

[win32_x86.zip](https://github.com/lief-project/LIEF/files/5836148/win32_x86.zip)

**Expected behavior**

`win32_x86_test.exe` should print `hello world!`.

**Environment (please complete the following information):**
 - System and Version : windows 10 (19041.746)
 - Target format : PE
 - LIEF commit version: 0.11.0-f58605f

**Additional context**

**Comment by mpuzz** [comment]
I reproduced the same issue using clang/mingw as compiler.
I think the problem lies in the fact that lief places the newly created IAT in a different section wrt to the original one (in my test cases the new section is called .l1).
Since the .text section is not modified (and it shouldn't be), the executable code still expects the pointers of the imported functions to be placed in the old section (usually called .idata).
The dynamic loader, however, uses the new IAT to bind the dynamic libraries.
As a result, each time the code invokes an imported function, it will fetch its address from one of the entries of the old IAT. It will then try to jump there and will raise an invalid access exception (the address is likely not mapped).

Ideally, the best way to handle this is by modifying the IAT _in place_, taking care to respect the same offsets for each entry of the IAT. This however is not possible in all cases, I think.

**Comment by invokerrrr** [comment]
In many cases, the content of the. Code (. Text) section cannot be modified (such as DLL injection). In my opinion, when rebuilding the binary file, we can keep the address of the old IAT table unchanged ( still in .idata ) , and only build the newly added library, which may make lief more compatible (although this will cause the old import library cannot add import functions).

**Comment by invokerrrr** [comment]
I have found [Detours](https://github.com/microsoft/Detours) perfectly solves dll inject problem.
