### ISSUE TITLE
" is not an ELF" printed before returning a lief.PE.Binary from file bytes

### ISSUE THREAD

**Issue by recvfrom** [lief-project/LIEF#541]
**Describe the bug**
` is not an ELF` gets printed to stderr when instantiating a lief.PE.Binary object from files bytes

**To Reproduce**
```python
>>> import lief
>>> fd = open('/tmp/00078542b6a64bfabac40491031d008839ca8e0097b7d9cad9b4628f8c532aa2', 'rb')
>>> data = fd.read()
>>> fd.close()
>>> lief.parse(list(data))
 is not an ELF
<lief.PE.Binary object at 0x7f75d8afbd88>
>>> lief.parse(data)
 is not an ELF
<lief.PE.Binary object at 0x7f75d8afbdc0>
>>> lief.parse('/tmp/00078542b6a64bfabac40491031d008839ca8e0097b7d9cad9b4628f8c532aa2')
<lief.PE.Binary object at 0x7f437eb0ed50>
```

**Expected behavior**
Don't print ` is not an ELF`

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Target: PE
 - LIEF commit version: `0.11.0-f58605f`

**Additional context**
N/A

**Comment by sudhackar** [comment]
This is due to 
https://github.com/lief-project/LIEF/blob/e875a8ffa279ddced72ea2f8add8e569791cf115/src/OAT/utils.cpp#L51
`Parser::parse`  at 
https://github.com/lief-project/LIEF/blob/e875a8ffa279ddced72ea2f8add8e569791cf115/src/Abstract/Parser.cpp#L91 
first verifies if its an OAT - which in turn calls `LIEF::ELF::Parser::parse` - trying tp parse the raw data as ELF and on failure prints it to log here 
https://github.com/lief-project/LIEF/blob/e875a8ffa279ddced72ea2f8add8e569791cf115/src/ELF/Parser.cpp#L172

**Comment by romainthomas** [comment]
This issue has been fixed while refactoring the code
