### ISSUE TITLE
[Feature] Pattern based search with ignored bytes

### ISSUE THREAD

**Issue by Ristovski** [lief-project/LIEF#574]
**Is your feature request related to a problem? Please describe.**
Having a way to search for byte patterns with ignored bytes (ex: `c7 44 24 04 ?? ?? ?? ab`) would be very useful.

**Describe the solution you'd like**
A function `search_pattern(pattern, mask)` that would search for the specified pattern while matching _any_ of the masked bytes.

**Describe alternatives you've considered**
Regex-based matching, but since `Section.content` returns a list of bytes (in Python), one would first need to make a `bytes()` copy, which is not very efficient memory-wise.

**Comment by romainthomas** [comment]
Hi @Ristovski 
There's already [these functions](https://lief.quarkslab.com/doc/latest/api/python/abstract.html#lief.Section.search) that could be used to search content.

I think that having a way to search for byte patterns is out-of-scope of this project but you could develop a plugin based on LIEF
to do that.

If you plan to develop such plugin, feel free to ping so that I can add a reference in the documentation.
