### ISSUE TITLE
impossible to parse a binary compiled with MSVC (cl.exe)

### ISSUE THREAD

**Issue by Unam3dd** [lief-project/LIEF#594]
good evening, I desperately tried to use lief to parse a binary that I compiled with the msvc compiler of microsoft, however lief does not manage to parse the binary, on the other hand when I compile this one with mingw, lief manages to parse it well, I checked well that my binary is well the good format PE? I would like to have some information thank you very much.
the red circle represents the binary that lief obviously can't parse, this one is compiled with msvc, and the blue one is exactly the same binary but compiled with mingw.

![image](https://user-images.githubusercontent.com/34691959/124187026-744fe800-dabd-11eb-847a-49c544c24380.png)

**Comment by romainthomas** [comment]
1. Please use code formatting instead of screenshot.
2.  > lief does not manage to parse the binary test 

     Did you check if the output of ``lief.parse("test.exe")`` is ``None`` ? 
3. Next time, please follow the issue template otherwise your issue won't be considerate (c.f [Incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+label%3AIncomplete+is%3Aclosed))
