### ISSUE TITLE
Please provide pypy package

### ISSUE THREAD

**Issue by inaryart** [lief-project/LIEF#651]
**Is your feature request related to a problem? Please describe.**
pypy compilation is too slow, especially in the github action every time you have to recompile

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by romainthomas** [comment]
Nop this is on purpose: https://github.com/lief-project/LIEF/issues/1032#issuecomment-1987253779.

**Comment by LecrisUT** [comment]
This can be greatly simplified:
- the coverage of python versions will diminish because with python 3.12+ you can build SABI wheels and cover all versions above with only 1 wheel
- the building of the system part can be done once and shared across python versions which would minimize the expensive part of the build process
- you can track a more minimal set of python environments during CI, but enable the full set when you are ready for release

Otherwise the issue is that the build-system fails when building from sdist. If that could be resolved than there would be less need for this.
