### ISSUE TITLE
MachO: Handle big endian/PPC binaries

### ISSUE THREAD

**Issue by fors4k3n** [lief-project/LIEF#708]
**Describe the bug**
MachO parser doesn't check byteorder when parsing header.

**To Reproduce**
Try to parse: [macho.zip](https://github.com/lief-project/LIEF/files/8778473/macho.zip)
password is 123456

**Environment (please complete the following information):**
 - System and Version : Win 10
 - Target format : Mach-O
 - LIEF commit version: c7b3ce3b

**Comment by romainthomas** [comment]
Thank you for the sample. Indeed LIEF is not able to parse PPC Mach-O file but it should support them.

**Comment by PaulDance** [comment]
I can reproduce the issue as well. Another sample if it can prove useful: the [WeaponX](https://www.virustotal.com/gui/file/5cf59f415ee67784227a2e9009ba9b3b3866d28d3d8f2b2c174368e1afc6ef96/detection) malware:
[weaponx.tar.gz](https://github.com/lief-project/LIEF/files/13319178/weaponx.tar.gz).

Fixing this issue would require refactoring a good portion of the code-base in order to be able to read integers in both possible byte-orders in all possible cases. Maybe [the way the Rust `object` crate handles it](https://github.com/gimli-rs/object/blob/master/src/endian.rs) can be of inspiration for this, for example with the [mach header](https://github.com/gimli-rs/object/blob/88554fa889c9ed9133a8488de720f2a08280d18e/src/macho.rs#L468-L488).

**Comment by romainthomas** [comment]
This issue has been resolved
