### ISSUE TITLE
Question: How to access the symbols in the PLT?

### ISSUE THREAD

**Issue by liona24** [lief-project/LIEF#762]
Hey.

I created a simple ELF binary like this:
```objdump
Disassembly of section .plt:

0000000000401020 <exit@plt-0x10>:
  401020:       ff 35 e2 2f 00 00       push   0x2fe2(%rip)        # 404008 <_GLOBAL_OFFSET_TABLE_+0x8>
  401026:       ff 25 e4 2f 00 00       jmp    *0x2fe4(%rip)        # 404010 <_GLOBAL_OFFSET_TABLE_+0x10>
  40102c:       0f 1f 40 00             nopl   0x0(%rax)

0000000000401030 <exit@plt>:
  401030:       ff 25 e2 2f 00 00       jmp    *0x2fe2(%rip)        # 404018 <exit@GLIBC_2.2.5>
  401036:       68 00 00 00 00          push   $0x0
  40103b:       e9 e0 ff ff ff          jmp    401020 <_init+0x20>

# snip

0000000000401126 <main>:
  401126:       55                      push   %rbp
  401127:       48 89 e5                mov    %rsp,%rbp
  40112a:       bf 01 00 00 00          mov    $0x1,%edi
  40112f:       e8 fc fe ff ff          call   401030 <exit@plt>
```

When I parse this using lief the only useful API I found is this:
```python
>>> b = lief.parse("/tmp/a.out")
>>> for i in b.pltgot_relocations:
...     print(i)
... 
404018    JUMP_SLOT 64  0         3         PLTGOT    exit
```

Considering `exit`, what I would want is the address in the PLT, i.e. 0x401030, but with this I can only get the GOT address, i.e. 0x404018. Can I somehow accomplish this in a reasonably easy way?
Thank you for your help.

**Comment by romainthomas** [comment]
Hello @liona24

It is **generically** complicated to achieve without a disassembler because to get this information, it requires to resolve the question "*which part of the binary uses the address pointed by the JUMP_SLOT relocation?*" (i.e. find the x-ref to `404018`)

On the other hand, the plt/got follows a *known* layout. The first entry is a jump to the resolver while the next entries **likely** follow the same order as the `JUMP_SLOT` relocations. Thus, and given the size of the plt sub, you can determine that exit in the plt is located at 0x401030. Note that this approach is not 100% reliable.
