### ISSUE TITLE
Mach-O regression: cannot parse empty universal static libary

### ISSUE THREAD

**Issue by isuruf** [lief-project/LIEF#873]
**Describe the bug**

Running `lief.parse` on the binary https://anaconda.org/isuruf/libclang_rt/15.0.7/download/libclang_rt.fuzzer_interceptors_osx.a
returns None whereas lief 0.11 series returned a Mach-O binary object.

**To Reproduce**

```python
>>> import lief
>>> lief.parse("libclang_rt.fuzzer_interceptors_osx.a")
```

**Expected behavior**
A clear and concise description of what you expected to happen (if applicable)

**Environment (please complete the following information):**
 - System and Version : macOS 10.13
 - Target format Mach-O
 - LIEF commit version: 0.13.0-0875ee24 and 0.12.3

**Additional context**

**Comment by romainthomas** [comment]
Hello @isuruf,

Actually this is not really a regression since the support for `.a` files is not implemented (yet) in LIEF. When this kind of file was provided to LIEF `0.11.5`'s parser, the binary was actually empty (you can try doing `print()` on the object returned).

The return value in `LIEF 0.13.0` is `None` which matches the unsupported feature.

**Comment by isuruf** [comment]
Thanks @romainthomas. Makes sense.
