### ISSUE TITLE
Abstract binary interface suffers from use-after-frees

### ISSUE THREAD

**Issue by momo5502** [lief-project/LIEF#910]
The abstract binary interface `src/Abstract/Binary.cpp` suffers from use-after-frees.

The methods `Binary::symbols`, `Binary::sections`, `Binary::relocations` (const as well as non-const variants) each return iterators of temporary containers destroyed after the call.

These methods call `get_abstract_symbols`, `get_abstract_sections` and `get_abstract_relocations`, which all return a temporary container object. That object is only alive within the scope of the `Binary` methods.

Returning iterators of those objects therefore causes memory corruptions.

**Comment by momo5502** [comment]
It was address sanitizer reporting the issue. However, I don't have the logs here. I will try to add more details tomorrow.

**Comment by romainthomas** [comment]
I did run ASAN/LSAN with this code: https://github.com/lief-project/LIEF/blob/ac47c2a9a00f525958acaa5161a3b65ea679ef1d/tests/sanitizer/sanitize_checks.cpp#L14-L35 without any issue. 

I close this issue but feel free to re-open an issue if you think that the problem is still there.
Note also that there is an issue template that must be used to provide (at least):

- The version (commit) of LIEF for which you did the tests
- Your environment (Windows?, Linux?, OSX?)

And in your case, the log from ASAN is more than required.

Thank you

**Comment by momo5502** [comment]
Neither can I reproduce this bug anymore. Sadly I didn't save the asan logs. From looking at the code, it seems that the iterator abstraction owns the container, so I don't see an issue with the code either. Closing it seems fine then. In case I can reproduce the erorr again, I will reopen the issue.
