### ISSUE TITLE
LIEF (MachO) returns a memory view with no data

### ISSUE THREAD

**Issue by palmerc** [lief-project/LIEF#928]
**Describe the bug**
When grabbing 4k pages with `get_content_from_virtual_address` it reaches an address of 0x1007f4000 then it starts returning empty memory views.

**To Reproduce**
Starting with image base and working up by 4k pages call get_content_from_virtual_address

**Expected behavior**
Data to be returned that is visibly there in HexFiend or similar tools

**Environment (please complete the following information):**
 - macOS 13.3.1
 - Mach-O
 - LIEF commit version: 0.13.1-b9a5f970

**Additional context**
Binary attached
[test_bin.zip](https://github.com/lief-project/LIEF/files/11685191/test_bin.zip)

**Comment by palmerc** [comment]
In addition once the process reaches __LINKEDIT memory view is negative. Starting at 0x100844000

**Comment by romainthomas** [comment]
Hello @palmerc, 

Actually the computation is correct: 

`0x1007f4000` is wrapped by the `__DATA` segment which has the following characteristics:

```
- Virtual address: 0x100780000
- Virtual size: 0xc4000 
- Offset: 0x780000
- Size: 0x74000
```

The virtual size is larger than the file size because of the `.bss`-like feature but the relative offset within this segment is: `0x100780000 - 0x1007f4000 = 0x74000`. Thus you ask to read `0x1000` from the offset `0x74000` of a blob that is exactly `0x74000` width. So it is 0

**Comment by palmerc** [comment]
You're right of course and I have fixed my error!
