### ISSUE TITLE
ELF files with large overlays take a long time and an enormous amount of RAM on performing `lief.ELF.parse()` and then accessing `elf.overlay`

### ISSUE THREAD

**Issue by cher-nov** [lief-project/LIEF#936]
**Describe the bug**

Parsing a ≈35 megabyte ELF file with a 1 gigabyte overlay takes about 1-2 seconds on a 2.4 GHz processor (i5-2430M).
Then, an attempt to evaluate `len(elf.overlay)` right after that consumes about 10 gigabytes of RAM, which is unacceptable.
The same file, but without the overlay, is processed in the blink of an eye on the same machine.

**To Reproduce**

1. Take the `app-linux` sample file from #935.

2. Create `overlay_long.py` near it with the following contents and run it using Python 3.x with the nightly `lief` package installed:
```python3
#!/usr/bin/env python3

import io
import lief

with open("app-linux", 'rb', 100 * 1024**2) as executable:
    print("parsing ELF...")
    elf = lief.ELF.parse(executable)
    print("> end parsing at", executable.tell())
    assert elf, "not an ELF file, I guess?.."

    print("seeking overlay...")
    executable.seek(-len(elf.overlay), io.SEEK_CUR)
    print("> position at", executable.tell())
```
You will notice that the script runs almost instantly.

3. Using any HEX editor, add 1,000,000,000 arbitrary bytes (≈1 gigabyte) to the end of the `app-linux` file.

4. Re-run the script. You will see the incorrect behavior described above.

**Environment:**

 - System and Version: Windows 7 x64 Service Pack 1
 - Target format: ELF
 - LIEF commit version: `0.14.0-57a59c56`

**Additional context**

As far as I can tell, this is because LIEF tries to read the entire overlay when loading the ELF file, which is wrong for several reasons:

1. This slows down the parsing of the file, while the user may not need the overlay.
2. This contradicts the semantics of reading from a stream, since not only a file I/O object can have a stream interface, but also, say, a compressed data unpacker or even a network connection (lol). In such a case, LIEF will consume everything until the end, although all it has to do is read **only the data directly related to the ELF file** and then stop. It's the user's task to determine what follows after it: an overlay or some other, unrelated data.

**Comment by romainthomas** [comment]
> As far as I can tell, this is because LIEF tries to read the entire overlay when loading the ELF file, which is wrong for several reasons:

Whilst I appreciate that you took time to open this issue, it might be wise
to ask questions first about specific design decisions rather than asserting: `which is wrong`.

That being said:

> 1. This slows down the parsing of the file, while the user may not need the overlay.

Keep in mind that LIEF also has a `write` support which means that when users
are doing `lief.parse(...).write("out")`, they expect `out` to be running as the original file.
Some binaries use the overlay section for their functionality. Thus, if you don't
parse it, you might break the re-written binary.

> 2. This contradicts the semantics of reading from a stream, since not only a
file I/O object can have a stream interface, but also, say, an unpacker of compressed data or even a network connection (lol). In such a case, LIEF will consume everything until the end, although all it has to do is read only the data directly related to the ELF file and then stop. It's the user's task to determine what follows after it: an overlay or some other, unrelated data.

I agree but I actually did benchmark with the following scenarios:

1. Implement on-demand `read(...)` from the Python IO (what you said)
2. Read all the buffer at once and then process this buffer

From what I can tell, the first implementation is slower than the second one (by magnitude) because
of back and forth between C++ and Python.
You pay a strong overhead doing so which might not be acceptable by the users.
Thus, I'll keep the second implementation, and if you really need a custom IO reader,
I recommend writing it in C++ and eventually exposing Python binding for your purpose.

**Comment by cher-nov** [comment]
> Whilst I appreciate that you took time to open this issue, it might be wise to ask questions first about specific design decisions rather than asserting: `which is wrong`.

English is not my native language, so I often express my thoughts in it inaccurately and oversimplified. Didn't mean to offend you in any way, sorry.

> Keep in mind that LIEF also has a `write` support which means that when users are doing `lief.parse(...).write("out")`, they expect `out` to be running as the original file. Some binaries use the overlay section for their functionality. Thus, if you don't parse it, you might break the re-written binary.

Maybe add then some kind of `overlay` parameter to `.parse()` or `ParserConfig`? With the next possible values:
- `None` (default) - consider all data up to the end of the stream as an overlay.
- `0` - consider that the file does not have any overlay.
- `x` (any other integer) - consider `x` bytes after executable data as its overlay.
