### ISSUE TITLE
Corrupted PE dos_stub after build()

### ISSUE THREAD

**Issue by alga81** [lief-project/LIEF#952]
**Describe the bug**
The write of the PE's dos_stub, corrupted after invoking `LIEF::PE::Builder::build()`.

**To Reproduce**
Reproduce with any Windows PE located at in_path:
```
int main(int argc, char** argv)
{
    auto pe = LIEF::PE::Parser::parse(in_path);
    LIEF::PE::Builder pe_builder(*pe);
    pe_builder.build();
    pe_builder.write(out_path);
    return 0;
}
```
out_path is corrupted:

<img width="1308" alt="dos_stub_bug" src="https://github.com/lief-project/LIEF/assets/94996651/27eb4fb1-2dd9-4582-bd9f-979c7f5e68c4">

**Expected behavior**
dos_stub section is correctly written to file.

**Environment (please complete the following information):**
 - System and Version : Windows 10 x64 (any version)
 - Target format: PE

**Comment by alga81** [comment]
I PR'd a tentative fix here: #951

**Comment by romainthomas** [comment]
Hi @alga81.

Thank you for pointing out this issue. The problem was actually in the `iostream` write interface which was implicitly buggy for non-const `span<uint8_t>`.

**Comment by alga81** [comment]
Hi @romainthomas, thanks for the clean fix.

**Comment by yype** [comment]
Hi folks,

I came across the same issue today because I was using the latest released version from pip, which hasn't included the fix to this issue yet.

I then looked at both of your patches, which are awesome and definitely can fix the issue. However, I find the root cause a bit interesting here:

## Recap
Before @romainthomas 's fix in https://github.com/lief-project/LIEF/commit/660f26ebf499d499d08d442a77ebc8cc835fab72, the following call:

https://github.com/lief-project/LIEF/blob/1f3b19ea213ee67388e1dc2672e989db5d5f0c43/src/PE/Builder.cpp#L453

actually instantiates the following template:

https://github.com/lief-project/LIEF/blob/1f3b19ea213ee67388e1dc2672e989db5d5f0c43/include/LIEF/iostream.hpp#L67

This resulted in the issue mentioned here: we are essentially copying some incorrect data of an incorrect size in memory to the dos_stub:

https://github.com/lief-project/LIEF/blob/1f3b19ea213ee67388e1dc2672e989db5d5f0c43/include/LIEF/iostream.hpp#L73

And since later on, the builder seeks to the offset of the PE header and continues:

https://github.com/lief-project/LIEF/blob/1f3b19ea213ee67388e1dc2672e989db5d5f0c43/src/PE/Builder.cpp#L480

The incorrect data only remains in the dos_stub and will not affect the size, layout, or other sections of the output binary, making it hard to notice.

## Concern
My concern here is about the implementation of that template:

https://github.com/lief-project/LIEF/blob/1f3b19ea213ee67388e1dc2672e989db5d5f0c43/include/LIEF/iostream.hpp#L67

Seems that the intention here is to match only integral types. Am I correct? If so, IMHO, the current implementation might have an issue since it also matches `span<T>`, which is not an integral type.

If that's the case, I wonder if `std::enable_if_t` should be used here. Replacing it with `std::enable_if_t` results in some other places being unable to match a candidate template function, which I suspect could be places that have the same issue.

Regards.

**Comment by romainthomas** [comment]
Hey @yype 

Thank you very much for taking time to provide your feedback on this fix. I really like your suggestion and to be honest I didn't went through the details of why `span` matched the `std::is_integral<Integer>::value`.

Thank a bunch for your comment!

**Comment by yype** [comment]
@romainthomas Thanks for the reply!

I think the following two templates kind of cover all possible cases (one for non-numeric and one for numeric):

https://github.com/lief-project/LIEF/blob/a900afb238c6eab98591e49702eddb562f99bff5/include/LIEF/iostream.hpp#L56
https://github.com/lief-project/LIEF/blob/a900afb238c6eab98591e49702eddb562f99bff5/include/LIEF/iostream.hpp#L75

This confused me a little bit. I went through the code again, and I think I can propose a better fix now.

Consider the following line:

https://github.com/lief-project/LIEF/blob/a900afb238c6eab98591e49702eddb562f99bff5/src/MachO/Builder.tcc#L514

Here `nl` is a struct filled with ints, and we still want to use the following implementation to write this variable:

https://github.com/lief-project/LIEF/blob/a900afb238c6eab98591e49702eddb562f99bff5/include/LIEF/iostream.hpp#L81

It seems that what we need here is [std::is_pod](https://en.cppreference.com/w/cpp/types/is_pod), which is later replaced by `is_standard_layout_v && is_trivial_v` according to the standard. ([Ref.](https://stackoverflow.com/a/48225882))

I've proposed a PR for this at https://github.com/lief-project/LIEF/pull/1007, in which I removed the overloaded function for `span<uint8_t>`, and merged the two templates into one template that uses `is_standard_layout_v && is_trivial_v`. 

I also removed one line in `src/ELF/Note.cpp`, which would cause a type mismatch problem. This line seemed redundant as `Note::write_string_at` already exists.

Let me know if this makes sense to you. Thanks!
